src/main/java/com/jobseek/speedjobs/config/WebConfig.java
src/main/java/com/jobseek/speedjobs/controller/AuthController.java
src/main/java/com/jobseek/speedjobs/domain/user/User.java
src/main/java/com/jobseek/speedjobs/service/AuthService.java
src/main/java/com/jobseek/speedjobs/utils/CookieUtil.java
src/main/java/com/jobseek/speedjobs/utils/JwtUtil.java

* 클라이언트에 액세스 토큰 쿠키, 리프레시 토큰 쿠키 전송
- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

feat: 쿠키 유틸 기능 추가

---

front/src/App.js
front/src/components/components/Styled.js
front/src/components/components/resume/ResumeBasic.js
front/src/components/components/resume/ResumeCareer.js
front/src/components/components/resume/ResumeEducation.js
front/src/components/components/resume/ResumeInputs.js
front/src/components/components/resume/ResumeSelf.js
front/src/components/components/resume/ResumeSkill.js
front/src/components/pages/MemberRegistration.js
front/src/components/pages/RecruitNew.js

- 이력서 레이아웃 styled 수정
- 오타 수정
- conatainer -> container
- style 필드에 styled 추가

style: 이력서 레이아웃 수정

---

front/src/components/components/Modal/Sns.js
src/main/java/com/jobseek/speedjobs/common/exception/OAuth2RegistrationException.java
src/main/java/com/jobseek/speedjobs/config/SecurityConfig.java
src/main/java/com/jobseek/speedjobs/config/WebConfig.java
src/main/java/com/jobseek/speedjobs/config/auth/CustomOAuth2UserService.java
src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationFailureHandler.java
src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java
src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
src/main/java/com/jobseek/speedjobs/dto/auth/TokenRequest.java
src/main/java/com/jobseek/speedjobs/service/AuthService.java

* redirect url 추후 수정
* validity 오타 수정
* 비밀번호 null 가능하도록 수정
- 소셜 로그인 지원(깃헙)
- redirect url 추후 수정
- validity 오타 수정
- 비밀번호 null 가능하도록 수정
- https://www.callicoder.com/spring-boot-security-oauth2-social-login-part-1/

feat: 깃헙 로그인

---

front/package-lock.json
front/package.json
front/src/components/components/Modal/Sns.js
src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
src/main/java/com/jobseek/speedjobs/domain/user/User.java

- 네이버 로그인
네이버 id와 카카오 이메일 아이디가 동일한 경우 email 유니크 오류 발생
-> user 도메인에서 email 유니크 key 삭제
style: 카카오 아이콘 변경
react-icon 사용해서 facebook 아이콘을 kakao 아이콘으로 변경
- 필요하면 첨부
- 참고 자료

feat: 네이버 로그인

---

src/main/java/com/jobseek/speedjobs/domain/recruit/Active.java
src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitRepository.java

공고 domain 추가

---

src/main/java/com/jobseek/speedjobs/domain/member/Member.java
src/main/java/com/jobseek/speedjobs/domain/member/MemberRepository.java
src/main/java/com/jobseek/speedjobs/domain/member/MemberService.java
src/main/java/com/jobseek/speedjobs/domain/resume/Career.java
src/main/java/com/jobseek/speedjobs/domain/resume/Certificate.java
src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
src/main/java/com/jobseek/speedjobs/domain/resume/Scholar.java
src/main/java/com/jobseek/speedjobs/domain/user/Role.java
src/main/java/com/jobseek/speedjobs/domain/user/User.java
src/test/java/com/jobseek/speedjobs/domain/member/MemberTest.java

- 개인유저 도메인 추가
이력서-자격/경력/학력 관계설정
- 필요하면 첨부
- 참고 자료

feat: 유저, 이력서 관련 엔티티 생성

---

src/main/java/com/jobseek/speedjobs/domain/corporation/Corporation.java
src/main/java/com/jobseek/speedjobs/domain/corporation/CorporationDetail.java
src/main/java/com/jobseek/speedjobs/domain/member/Member.java
src/main/java/com/jobseek/speedjobs/domain/post/Post.java
src/main/java/com/jobseek/speedjobs/domain/post/PostDetail.java
src/main/java/com/jobseek/speedjobs/domain/recruit/Experience.java
src/main/java/com/jobseek/speedjobs/domain/recruit/Position.java
src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitDetail.java
src/main/java/com/jobseek/speedjobs/domain/recruit/Status.java
src/main/java/com/jobseek/speedjobs/domain/resume/Career.java
src/main/java/com/jobseek/speedjobs/domain/resume/Certificate.java
src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
src/main/java/com/jobseek/speedjobs/domain/resume/Scholar.java
src/main/java/com/jobseek/speedjobs/domain/user/User.java
src/main/java/com/jobseek/speedjobs/dto/post/PostResponseDto.java
src/main/java/com/jobseek/speedjobs/dto/post/PostSaveDto.java

- Recruit(공고) 추가 및, detail들 Embedded로 생성
- 
- 구글링

feat: Domain 추가본

---

src/main/java/com/jobseek/speedjobs/controller/TagController.java
src/main/java/com/jobseek/speedjobs/domain/post/Post.java
src/main/java/com/jobseek/speedjobs/domain/tag/PostTag.java
src/main/java/com/jobseek/speedjobs/domain/tag/Tag.java
src/main/java/com/jobseek/speedjobs/dto/post/PostSaveDto.java
src/main/java/com/jobseek/speedjobs/dto/tag/TagResponses.java
src/main/java/com/jobseek/speedjobs/dto/tag/TagUpdateRequest.java
src/main/java/com/jobseek/speedjobs/service/PostService.java
src/main/java/com/jobseek/speedjobs/service/TagService.java
src/main/java/com/jobseek/speedjobs/service/UserService.java

- 앞선 PR에 빠진 커밋 보충
- 태그 crud 보충
- 필요하면 첨부
- 참고 자료

feat: 태그, 게시물 보충

---

src/main/java/com/jobseek/speedjobs/controller/RecruitController.java
src/main/java/com/jobseek/speedjobs/dto/post/PostResponse.java
src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitResponse.java
src/main/java/com/jobseek/speedjobs/dto/tag/TagMap.java
src/main/java/com/jobseek/speedjobs/service/RecruitService.java
src/main/resources/http/recruit.http

- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

feat: 공고 페이징 추가

---

front/src/App.js
front/src/components/components/Profile/ProfileDetails.js
front/src/components/components/Profile/ProfileImage.js
front/src/components/components/Profile/ProfileInputTel.js
front/src/components/components/Profile/ProfileInputs.js
front/src/components/components/Profile/ProfileModify.js
front/src/components/components/Profile/ProfileTextarea.js
front/src/components/components/Styled.js
front/src/components/components/resume/ResumeBasic.js
front/src/components/components/resume/ResumeCareer.js
front/src/components/components/resume/ResumeCertificate.js
front/src/components/pages/Community.js
front/src/components/pages/Profile.js
front/src/components/pages/ProfileMd.js
front/src/reducers/profile.js
front/src/sagas/profile.js
src/main/java/com/jobseek/speedjobs/config/auth/CustomOAuth2UserService.java
src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
src/main/java/com/jobseek/speedjobs/domain/company/Company.java
src/main/java/com/jobseek/speedjobs/domain/member/Member.java
src/main/java/com/jobseek/speedjobs/domain/user/User.java
src/main/java/com/jobseek/speedjobs/dto/user/UserInfoResponse.java
src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
src/main/java/com/jobseek/speedjobs/dto/user/member/MemberInfoResponse.java
src/main/java/com/jobseek/speedjobs/dto/user/member/MemberUpdateRequest.java
src/main/java/com/jobseek/speedjobs/service/UserService.java
src/main/resources/http/user.http

- 요구사항
- 개인정보 조회 기능 추가
- 개인정보 수정하고 조회할때 오류 수정
- /user/me에서 name보내준거 nickname으로 변경
- 소셜 로그인할 때 name에다 저장했는데 nickname에 저장
- 필요하면 첨부
- 참고 자료

feat: 개인정보 수정 기능 추가

---

src/main/java/com/jobseek/speedjobs/config/auth/CustomOAuth2UserService.java
src/main/java/com/jobseek/speedjobs/controller/PostController.java
src/main/java/com/jobseek/speedjobs/controller/RecruitController.java
src/main/java/com/jobseek/speedjobs/domain/member/Member.java
src/main/java/com/jobseek/speedjobs/domain/recruit/Experience.java
src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
src/main/java/com/jobseek/speedjobs/dto/post/PostResponse.java
src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitListResponse.java
src/main/java/com/jobseek/speedjobs/service/PostService.java
src/main/java/com/jobseek/speedjobs/service/RecruitService.java
src/main/resources/http/recruit.http

- 공고 찜하기 기능 추가
- 게시글 조회 시 로그인 유저의 찜 여부 확인
- 소셜 로그인 시 닉네임과 이미지 업데이트 안하도록 수정
- enum 대문자 수정
- 공고에 회사 정보 들어가도록 수정
- 모든 게시글, 공고마다 favorite(이미 찜하였는지) 추가
- 필요하면 첨부
- 참고 자료

feat: 공고 찜하기 기능 추가

---

front/src/App.js
front/src/components/components/Profile/ProfileDetails2.js
front/src/components/pages/Profile.js
front/src/components/pages/ProfileMd.js
front/src/components/pages/ProfileMd2.js
front/src/reducers/profile.js
front/src/sagas/profile.js

- 요구사항
- 기업회원 조회, 수정 페이지 추가
- profileSage에서 role을 기준으로 분기시킴
- 필요하면 첨부
- 참고 자료

feat: 기업회원 조회, 수정 페이지 추가

---

front/src/App.js
front/src/components/components/SideMenu.js
front/src/components/components/Styled.js
front/src/components/pages/Profile2.js
front/src/components/pages/ResumeList.js
front/src/sagas/profile.js

- 회원탈퇴 페이지 추가
- 이력서 목록 페이지 추가
- 요구사항
- 회원탈퇴 페이지 추가
- 이력서 목록 페이지 추가
- 필요하면 첨부
- 참고 자료

feat: 개인회원 탈퇴 기능 추가

---

build.gradle
front/src/sagas/recruit.js
src/main/java/com/jobseek/speedjobs/config/QuerydslConfig.java
src/main/java/com/jobseek/speedjobs/controller/PostController.java
src/main/java/com/jobseek/speedjobs/domain/post/Post.java
src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
src/main/java/com/jobseek/speedjobs/domain/tag/Tag.java
src/main/java/com/jobseek/speedjobs/dto/post/PostListResponse.java
src/main/java/com/jobseek/speedjobs/dto/post/PostSearchCondition.java
src/main/java/com/jobseek/speedjobs/service/PostService.java
src/main/java/com/jobseek/speedjobs/utils/QueryDslUtil.java
src/main/resources/http/post.http
src/test/java/com/jobseek/speedjobs/service/PostServiceTest.java

- 게시글 검색 기능
- 공고 url 수정
- post, tag 엔티티 약간 수정
- querydsl 추가
- querydsl 유틸리티 추가
- 필요하면 첨부
- 참고 자료

feat: 게시글 검색 기능 추가

---

src/main/java/com/jobseek/speedjobs/controller/UserController.java
src/main/java/com/jobseek/speedjobs/domain/company/Company.java
src/main/java/com/jobseek/speedjobs/domain/member/Member.java
src/main/java/com/jobseek/speedjobs/domain/post/Post.java
src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
src/main/java/com/jobseek/speedjobs/domain/user/User.java
src/main/java/com/jobseek/speedjobs/dto/user/UserCheckRequest.java
src/main/java/com/jobseek/speedjobs/service/UserService.java
src/main/resources/data.sql
src/main/resources/http/post.http
src/main/resources/http/user.http
src/test/java/com/jobseek/speedjobs/domain/post/PostRepositoryTest.java
src/test/java/com/jobseek/speedjobs/service/PostServiceTest.java
src/test/java/com/jobseek/speedjobs/service/UserServiceTest.java

- 회원 탈퇴
- 도메인 약간 변경
- 유저에서 양방향으로 연결
- 일반회원, 기업회원 같은 uri 공유
- 필요하면 첨부
- 참고 자료

feat: 회원 탈퇴 기능 추가

---

front/src/auth/interceptor.js
front/src/components/components/Nav/NavSearch.js
front/src/components/components/Search/SearchArea.js
front/src/components/pages/ProfileMd.js
front/src/components/pages/ProfileMd2.js

* 게시물 검색 기능구현
- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

feat: 검색기능구현

---

front/src/components/components/Post.js
front/src/components/pages/PostDetail.js
front/src/components/pages/PostModify.js
front/src/sagas/post.js

* 게시물 수정
* 찜할때 숫자 안오르는 현상 해결
- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

fix: 게시물 수정

---

front/package-lock.json
front/package.json
front/src/components/components/Profile/ProfileImage.js
front/src/components/components/resume/ResumeBasic.js
front/src/components/pages/Profile.js
front/src/components/pages/Profile2.js
front/src/components/pages/ProfileMd.js
front/src/components/pages/ProfileMd2.js
front/src/components/pages/Resume.js
front/src/reducers/index.js
front/src/reducers/resume.js
front/src/sagas/index.js
front/src/sagas/profile.js
front/src/sagas/resume.js
src/main/java/com/jobseek/speedjobs/dto/resume/ResumeRequest.java

- 요구사항
- 이력서 기본사항 redux 연동 확인
- 기업회원 & 개인회원 회원탈퇴 합침
- 회원탈퇴시 비밀번호 확인 기능 추가 (소셜로그인은 안됨)
- 회원탈퇴 버그 발견
- 필요하면 첨부
- 참고 자료

feat: 이력서 & 개인정보 페이지 기능 추가

---

front/src/components/components/Search/SearchArea.js
front/src/components/pages/Community.js
front/src/components/pages/Recruitment.js
front/src/reducers/post.js
front/src/reducers/recruit.js
front/src/sagas/post.js
front/src/sagas/recruit.js

* 공고 검색 추가
- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

feat: 공고 검색추가

---

src/main/java/com/jobseek/speedjobs/config/SwaggerConfig.java
src/main/java/com/jobseek/speedjobs/controller/FileController.java
src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
src/main/resources/http/post.http
src/main/resources/http/recruit.http

- 태그 있는 게시글, 공고가 포함되면 다른 결과가 무시되는 현상 해결
- 게시글(제목 + 내용), 공고(제목 + 기업명) 통합 검색 수정
- queryRepository 로직 수정
- 파일 컨트롤러 이동
- 스웨거 베이스 패키지 복구
- 필요하면 첨부
- 참고 자료

fix: 게시글, 공고 검색 수정

---

front/src/components/components/Registration/RegisterContents.js
src/main/java/com/jobseek/speedjobs/config/ScheduledConfig.java
src/main/java/com/jobseek/speedjobs/controller/UserController.java
src/main/java/com/jobseek/speedjobs/domain/recruit/Recruit.java
src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitRepository.java
src/main/java/com/jobseek/speedjobs/domain/resume/details/Career.java
src/main/java/com/jobseek/speedjobs/domain/resume/details/Certificate.java
src/main/java/com/jobseek/speedjobs/domain/resume/details/Scholar.java
src/main/java/com/jobseek/speedjobs/domain/user/Role.java
src/main/java/com/jobseek/speedjobs/domain/user/User.java
src/main/java/com/jobseek/speedjobs/domain/user/UserQueryRepository.java
src/main/java/com/jobseek/speedjobs/domain/user/UserRepository.java
src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitRequest.java
src/main/java/com/jobseek/speedjobs/dto/user/UserListResponse.java
src/main/java/com/jobseek/speedjobs/dto/user/UserSearchCondition.java
src/main/java/com/jobseek/speedjobs/service/RecruitService.java
src/main/java/com/jobseek/speedjobs/service/UserService.java
src/main/java/com/jobseek/speedjobs/utils/MailUtil.java
src/main/resources/META-INF/additional-spring-configuration-metadata.json
src/main/resources/http/user.http
src/main/resources/templates/email.html
src/test/java/com/jobseek/speedjobs/service/UserServiceTest.java

- 회원 조회(관리자만 가능)
- 끝난 공고 매시간마다 자동 삭제
- 기업회원 가입 로직 변경(이메일 인증 -> ROLE_GUEST -> 관리자가 가입 승인 -> ROLE_COMPANY
- 스케쥴링 추가
- 서버 url 추가
- yaml파일 변경
- 필요하면 첨부
- 참고 자료

feat: 회원 조회 및 공고 스케쥴링

---

src/main/java/com/jobseek/speedjobs/advice/RestExceptionHandler.java
src/main/java/com/jobseek/speedjobs/advice/dto/ValidResponse.java
src/main/java/com/jobseek/speedjobs/common/ErrorCode.java
src/main/java/com/jobseek/speedjobs/config/auth/LoginUserArgumentResolver.java
src/main/java/com/jobseek/speedjobs/config/auth/exception/LoginException.java
src/main/java/com/jobseek/speedjobs/controller/RecruitController.java
src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
src/main/java/com/jobseek/speedjobs/dto/user/UserCheckRequest.java
src/main/java/com/jobseek/speedjobs/service/RecruitService.java
src/main/resources/http/user.http

- Errorcode 수정, 추가(json 필드 에러 추가)
- 공고, 게시글 쿼리 수정
- 필요하면 첨부
- 참고 자료

fix: 예외 수정 및 추가, 쿼리문 수정

---

front/src/components/components/Modal/Login.js
front/src/components/components/Modal/SignUp.js
front/src/components/components/Registration/RegisterContents.js
front/src/components/components/Styled.js
front/src/components/components/comment/Comment.js
front/src/components/components/comment/PostDetailComment.js
front/src/components/pages/Community.js
front/src/components/pages/home/AnnounceCard.js
front/src/reducers/comment.js
front/src/sagas/comment.js

- 요구사항
- 게시글 검색바 수정중
- 필요하면 첨부
- 참고 자료

fix: 게시글 검색바 수정중

---

front/src/auth/interceptor.js
front/src/components/admin/component/AdminAlert.js
front/src/components/admin/component/SideBar.js
front/src/components/admin/component/TagList.js
front/src/components/admin/page/AdminHome.js
front/src/components/admin/page/BannerSetting.js
front/src/components/admin/page/CompanySetting.js
front/src/components/admin/page/Login.js
front/src/components/components/Search/SearchArea.js
front/src/components/components/Styled.js
front/src/components/components/tag/TagSelector.js
front/src/components/pages/CommuLike.js
front/src/components/pages/RecruitLike.js
front/src/reducers/admin.js
front/src/reducers/tag.js
front/src/sagas/admin.js
front/src/sagas/tag.js

* admin 배너 조회기능추가
* 태그 수정 삭제 기능추가
* admin 알람 리덕스 추가
- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

feat: admin 배너조회 태그 수정 삭제 추가 기능 추가

---

front/src/App.js
front/src/components/components/Post/PostList.js
front/src/components/components/Profile/IndividualDetails.js
front/src/components/components/SideMenu.js
front/src/components/components/Styled.js
front/src/components/components/SubmitItem.js
front/src/components/components/comment/Comment.js
front/src/components/components/comment/PostDetailComment.js
front/src/components/pages/Community.js
front/src/components/pages/MyPosts.js
front/src/components/pages/MyRecruitments.js
front/src/components/pages/SubmitList.js
front/src/components/pages/profile/IndividualModify.js
front/src/components/pages/profile/Profile.js
front/src/sagas/post.js
front/src/sagas/recruit.js

- 공고지원 이력서목록 페이지 추가
- 게시글목록에서 검색바 수정
- 기업회원이 작성한 게시글목록 수정
- 기업회원이 작성한 공고글목록 수정
- 게시글목록 순서변경버튼 수정
- 필요하면 첨부
- 참고 자료

feat: 공고지원 이력서목록 페이지 추가

---

front/src/components/components/Modal/Modal.js
front/src/components/components/Nav/NavDrop.js
front/src/components/components/Nav/NavMenu.js
front/src/components/components/Post/PostList.js
front/src/components/components/Registration/RegisterInput.js
front/src/components/components/SubmitItem.js
front/src/components/data/mapLink.js
front/src/components/pages/MyRecruitments.js
front/src/components/pages/RecruitmentDetail.js
front/src/components/pages/SubmitList.js
front/src/reducers/company.js
front/src/reducers/resume.js
front/src/sagas/company.js
front/src/sagas/resume.js
src/main/java/com/jobseek/speedjobs/advice/RestExceptionHandler.java
src/main/java/com/jobseek/speedjobs/config/auth/exception/ExpiredTokenException.java
src/main/java/com/jobseek/speedjobs/config/auth/exception/InvalidTokenException.java
src/main/resources/http/apply.http

- 공고에서 이력서 지원이벤트 추가
- 기업회원이 공고에 지원한 이력서 조회 추가
- 기업회원가입 경고메세지 수정
- 기업회원일 경우 헤더 드롭다운메뉴 경로 수정
- 필요하면 첨부
- 참고 자료

feat: 공고에 이력서 지원하기 추가

---

src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
src/main/java/com/jobseek/speedjobs/dto/post/PostSearchCondition.java
src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitSearchCondition.java

- 생성일 기준 조회
- 변경사항
- 필요하면 첨부
- 참고 자료

feat: 게시글, 공고 조회 조건 추가

---

front/package-lock.json
front/package.json
front/src/App.js
front/src/components/components/Modal/Login.js
front/src/components/components/Modal/SignUp.js
front/src/components/components/RecruitAdd/AnnounceLocation.js
front/src/components/components/RecruitAdd/AnnouncementDate.js
front/src/components/components/RecruitAdd/AnnouncementInfo.js
front/src/components/components/RecruitAdd/CompanySummaryInfo.js
front/src/components/components/RecruitAdd/RecruitAddContents.js
front/src/components/components/Styled.js
front/src/components/components/SubmitItem.js
front/src/components/components/banner/Banner.js
front/src/components/components/comment/Comment.js
front/src/components/components/comment/PostDetailComment.js
front/src/components/components/resume/ResumeCareer.js
front/src/components/data/DaumAddress.js
front/src/components/data/registerCheck.js
front/src/components/data/signUpCheck.js
front/src/components/pages/Community.js
front/src/components/pages/PostDetail.js
front/src/components/pages/PostModify.js
front/src/components/pages/RecruitModify.js
front/src/components/pages/Recruitment.js
front/src/components/pages/RecruitmentDetail.js
front/src/reducers/recruit.js
front/src/sagas/post.js
front/src/sagas/recruit.js
src/main/resources/http/post.http
src/main/resources/http/recruit.http

- 도로명주소 api 추가
- 공고 삭제 추가
- 공고 상세페이지에서 요약 파트 수정
- 공고 수정페이지 작성중
- role_admin인 경우 삭제버튼 활성화
- 공고목록에서 태그검색&검색바 추가
- 필요하면 첨부
- 참고 자료

feat: 도로명주소 api 추가

---

front/src/App.js
front/src/components/components/resume/ResumeBasicMd.js
front/src/components/components/resume/ResumeCareerMd.js
front/src/components/components/resume/ResumeCertificateMd.js
front/src/components/components/resume/ResumeContentsMd.js
front/src/components/components/resume/ResumeEducationMd.js
front/src/components/components/resume/ResumeSelfMd.js
front/src/components/components/resume/ResumeSkill.js
front/src/components/components/resume/ResumeSkillMd.js
front/src/components/components/resume/ResumeWow.js
front/src/components/pages/ResumeDetails.js
front/src/components/pages/ResumeModify.js
front/src/components/pages/ResumeTotal.js
front/src/sagas/resume.js
src/main/java/com/jobseek/speedjobs/controller/ResumeController.java
src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
src/main/java/com/jobseek/speedjobs/dto/resume/ResumeRequest.java
src/main/java/com/jobseek/speedjobs/service/ResumeService.java

- 이력서 수정
- 백 수정(태그 이름, 빠진 변수 추가)
- 이력서 수정
- 백 수정(태그 이름, 빠진 변수 추가)
- 변경사항
- 필요하면 첨부
- 참고 자료

feat: 이력서 기능 추가

---

front/src/components/components/Nav/NavLink.js
front/src/components/components/Nav/NavSearch.js
front/src/components/components/Notification/ModalAlert.js
front/src/components/components/Post/PostList.js
front/src/components/components/Profile/ProfileTextarea.js
front/src/components/includes/Header.js
front/src/components/pages/profile/CorporateModify.js
front/src/components/pages/profile/Profile.js
front/src/components/pages/profile/Withdrawal.js
front/src/sagas/comment.js
front/src/sagas/company.js
front/src/sagas/recruit.js
front/src/sagas/resume.js
src/test/java/com/jobseek/speedjobs/service/TagServiceTest.java

- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

style: prettier 재적용

---

front/src/auth/interceptor.js
front/src/auth/setCookie.js
front/src/components/pages/Community.js
front/src/components/pages/PostDetail.js
front/src/components/pages/Recruitment.js
front/src/sagas/recruit.js
front/src/sagas/user.js

* 로그인 쿠키설정
* 페이징 오류 fix
* 게시글 오류 fix
- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

fix:로그인 쿠키설정

---

front/src/components/components/RecruitAdd/AnnounceLocation.js
front/src/components/components/RecruitAdd/AnnouncementDate.js
front/src/components/components/RecruitAdd/AnnouncementInfo.js
front/src/components/components/RecruitAdd/CompanySummaryInfo.js
front/src/components/components/RecruitAdd/RecruitAddContents.js
front/src/components/components/Styled.js
front/src/components/components/SubmitItem.js
front/src/components/data/DaumAddress.js
front/src/components/pages/RecruitAdd.js
front/src/components/pages/Recruitment.js
front/src/components/pages/RecruitmentDetail.js
front/src/sagas/profile.js
src/main/resources/http/post.http
src/main/resources/http/recruit.http

- 공고 추가페이지 작성
- 도로명주소를 카카오지도에 표시하도록 수정
- 필요하면 첨부
- 참고 자료

Feat: 공고 추가페이지 작성

---

src/main/java/com/jobseek/speedjobs/controller/UserController.java
src/main/java/com/jobseek/speedjobs/domain/company/CompanyDetail.java
src/main/java/com/jobseek/speedjobs/domain/post/Post.java
src/main/java/com/jobseek/speedjobs/domain/post/PostQueryRepository.java
src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitQueryRepository.java
src/main/java/com/jobseek/speedjobs/domain/resume/ResumeQueryRepository.java
src/main/java/com/jobseek/speedjobs/domain/user/UserQueryRepository.java
src/main/java/com/jobseek/speedjobs/dto/post/PostRequest.java
src/main/java/com/jobseek/speedjobs/dto/post/PostSearchCondition.java
src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitResponse.java
src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitSearchCondition.java
src/main/java/com/jobseek/speedjobs/dto/user/UserListResponse.java
src/main/java/com/jobseek/speedjobs/dto/user/UserSaveRequest.java
src/main/java/com/jobseek/speedjobs/dto/user/company/CompanyInfoResponse.java
src/main/java/com/jobseek/speedjobs/dto/user/company/CompanyUpdateRequest.java
src/main/java/com/jobseek/speedjobs/service/UserService.java
src/test/java/com/jobseek/speedjobs/service/PostServiceTest.java

- 기업 정보 수정에서 기업 주소 수정 가능
- 게시글, 공고 검색 조건 추가(작성자 아이디)
- 공고 조회에 작성일자 추가
- company rating 컬럼 삭제
- 필요하면 첨부
- 참고 자료

feat: 기업 정보 수정 및 검색 조건 추가

---

front/src/App.js
front/src/auth/interceptor.js
front/src/components/components/Cards.js
front/src/components/components/Post.js
front/src/components/components/Styled.js
front/src/components/components/Tags.js
front/src/components/components/banner/Banner.js
front/src/components/pages/Community.js
front/src/components/pages/Home.js
front/src/components/pages/NotFound.js
front/src/components/pages/PostDetail.js
front/src/components/pages/Recruitment.js
front/src/components/pages/SocialLogin.js
front/src/index.js
front/src/reducers/user.js
front/src/sagas/user.js
src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java

* 소셜로그인이 먼저 다른 컴포넌트를 지난뒤에 로그인
* not found 페이지 추가
* 레이아웃 조절
- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

fix: 소셜로그인 방식변경

---

front/package-lock.json
src/main/java/com/jobseek/speedjobs/domain/BaseTimeEntity.java
src/main/java/com/jobseek/speedjobs/domain/company/Company.java
src/main/java/com/jobseek/speedjobs/domain/member/Member.java
src/main/java/com/jobseek/speedjobs/domain/user/User.java
src/main/java/com/jobseek/speedjobs/dto/recruit/RecruitRequest.java
src/main/java/com/jobseek/speedjobs/service/TagService.java
src/test/java/com/jobseek/speedjobs/service/RecruitServiceTest.java
src/test/java/com/jobseek/speedjobs/service/TagServiceTest.java

- User, Member, Company Annotation 수정 @SuperBuilder
- 공고 CRUD 테스트 추가

feat: 공고 테스트 추가

---

front/src/components/components/RecruitAdd/AnnouncementDate.js
front/src/components/components/RecruitAdd/AnnouncementInfo.js
front/src/components/components/RecruitAdd/CompanySummaryInfo.js
front/src/components/components/RecruitAdd/RecruitAddContents.js
front/src/components/pages/RecruitAdd.js
front/src/components/pages/RecruitModify.js
front/src/components/pages/Recruitment.js
front/src/components/pages/RecruitmentDetail.js
front/src/components/pages/ResumeDetails.js
front/src/reducers/recruit.js
front/src/sagas/recruit.js
src/main/resources/http/recruit.http

- 공고수정 페이지 작성
- 공고목록 페이지에서 연봉/채용상태별 태그검색 추가
- 공고상세 페이지에서 평균정보/회사주소 표시
- 공고상세 페이지에서 일반회원만 지원하기/찜하기 버튼 표시
- 이력서상세 페이지에서 기업계정은 수정버튼 숨기기
- 필요하면 첨부
- 참고 자료

feat: 공고수정 페이지 작성

---

front/src/components/components/Post.js
front/src/components/components/Styled.js
front/src/components/pages/PostDetail.js
front/src/components/pages/RecruitmentDetail.js

* 검색창 레이아웃 조절
* 공고 레이아웃 조절
* 태그 모바일화면 1개이상일경우 +n 으로 변경
* 전체적 폰트 굵기 조절
- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

fix: 레이아웃조절

---

front/src/components/components/Profile/CorporateDetails.js
front/src/components/components/Registration/RegisterContents.js
front/src/components/components/resume/ResumeBasic.js
front/src/components/pages/Resume.js
front/src/components/pages/ResumeDetails.js
front/src/components/pages/ResumeModify.js
front/src/components/pages/ResumeTotal.js
front/src/components/pages/profile/CorporateModify.js
front/src/components/pages/profile/IndividualModify.js
front/src/components/pages/profile/Profile.js
front/src/reducers/resume.js
front/src/sagas/resume.js

- 요구사항
- datepicker 오류 수정
- 리덕스 오류 수정
- 이력서 목록 오류 수정
- 기업 회원가입 닉네임 null 오류 수정
- 
- 필요하면 첨부
- 참고 자료

feat: 오류 수정

---

src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java
src/main/java/com/jobseek/speedjobs/config/auth/OAuthAttributes.java
src/main/java/com/jobseek/speedjobs/controller/ResumeController.java
src/main/java/com/jobseek/speedjobs/domain/resume/ResumeQueryRepository.java
src/main/java/com/jobseek/speedjobs/domain/user/UserQueryRepository.java

- distinct 삭제
- 멤버는 본인이 쓴 이력서만 조회 가능하고, 기업 회원과 관리자는 모든 이력서를 조회할 수 있다.
- 변경사항
- 필요하면 첨부
- 참고 자료

fix: 쿼리문 수정

---

front/src/components/components/RecruitAdd/AnnouncementInfo.js
front/src/components/components/Styled.js
front/src/components/pages/RecruitModify.js
front/src/components/pages/Recruitment.js
front/src/components/pages/SubmitList.js
src/main/java/com/jobseek/speedjobs/config/auth/OAuth2AuthenticationSuccessHandler.java
src/main/resources/http/resume.http

- 요구사항
- 공고목록 페이지 검색태그/검색바 모바일 위치 조정중
- 필요하면 첨부
- 참고 자료

fix: 공고목록 페이지 검색태그/검색바 모바일 위치 조정중

---

front/src/components/components/Post.js
front/src/components/components/RecruitAdd/AnnouncementInfo.js
front/src/components/components/RecruitAdd/CompanySummaryInfo.js
front/src/components/components/RecruitAdd/RecruitAddContents.js
front/src/components/components/Styled.js
front/src/components/pages/CommuLike.js
front/src/components/pages/Community.js
front/src/components/pages/PostDetail.js
front/src/components/pages/RecruitAdd.js
front/src/components/pages/RecruitLike.js
front/src/components/pages/RecruitModify.js
front/src/components/pages/Recruitment.js

* 커뮤니티,공고 검색창 조절
* 공고 추가,수정 레이아웃 조절
* 페이지네이션 오류수정
- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

fix: 레이아웃조절2

---

front/src/components/components/Chatting/ChatIcon.js
front/src/components/components/ResumeItem.js
front/src/components/components/SubmitItem.js
front/src/components/pages/CommuLike.js
front/src/components/pages/RecruitLike.js
front/src/components/pages/Recruitment.js
front/src/components/pages/RecruitmentDetail.js
front/src/components/pages/SubmitList.js
front/src/sagas/resume.js
src/main/java/com/jobseek/speedjobs/dto/apply/MemberResponse.java
src/main/java/com/jobseek/speedjobs/dto/resume/ResumeResponse.java

- 기업회원을 위한 공개이력서 목록 페이지 추가
- 공고상세 페이지에서 공고상태에 따라 지원하기/찜하기 버튼 표시
- 공고채팅 버튼 오류 수정
- 공고에 지원한 이력서 조회 페이지 수정 
- 필요하면 첨부
- 참고 자료

feat: 공개이력서 목록 페이지 추가

---

front/src/components/components/Notification/PopUp.js
front/src/components/components/resume/ResumeBasic.js
front/src/components/data/DaumAddress.js
front/src/components/data/mapLink.js
front/src/components/includes/Header.js
front/src/components/pages/Resume.js
front/src/components/pages/ResumeDetails.js
front/src/components/pages/profile/CorporateModify.js
front/src/components/pages/profile/Withdrawal.js

- 요구사항
- 이력서 알림 기능 추가(등록, 수정, 삭제)
- 이력서 레이아웃 수정(조회페이지)
- mapLink 경로 수정
(닉네임 클릭시 계정관리 페이지 이동)
- 이력서 이메일 폼 추가(등록, 수정)
- 회원탈퇴 이벤트 기능 추가 => enter 누르면 탈퇴 가능
- 필요하면 첨부
- 참고 자료

fix: 이력서, 프로필 오류 수정

---

front/src/components/components/RecruitAdd/AnnouncementInfo.js
front/src/components/components/Styled.js
front/src/components/components/Tags.js
front/src/components/pages/Community.js
front/src/components/pages/Recruitment.js
front/src/components/pages/RecruitmentDetail.js
src/main/resources/http/post.http
src/main/resources/http/recruit.http

- 요구사항
- 목록페이지에서 검색태그 디자인 수정
- 지원할 이력서목록 모바일 레이아웃 수정
- 필요하면 첨부
- 참고 자료

fix: 검색태그 디자인 수정

---

front/src/components/components/RecruitAdd/AnnouncementInfo.js
front/src/components/components/ResumeItem.js
front/src/components/components/SubmitItem.js
front/src/components/pages/Community.js
front/src/components/pages/SubmitList.js

- 요구사항
- 공고추가 페이지에서 사진추가 로직 수정 (클릭시 사진추가 가능)
- 공고에 지원된 이력서목록 모바일 레이아웃 수정
- 필요하면 첨부
- 참고 자료

fix: 공고추가 페이지에서 사진추가 로직 수정

---

front/src/components/admin/component/Alert.js
front/src/components/admin/component/MemberInfo.js
front/src/components/admin/component/SideBar.js
front/src/components/admin/data/PostChart.js
front/src/components/admin/page/BannerSetting.js
front/src/components/admin/page/MemberSetting.js
front/src/components/components/ResumeItem.js
front/src/components/components/banner/Banner.js
front/src/reducers/admin.js
front/src/sagas/admin.js
src/main/java/com/jobseek/speedjobs/config/SecurityConfig.java
src/main/java/com/jobseek/speedjobs/controller/BannerController.java
src/main/resources/http/banner.http

* admin 배너세팅 추가
* admin 유저 삭제 추가
* admin 게시글 관리 삭제
- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

feat: admin 배너세팅

---

front/src/components/components/banner/Banner.js
front/src/components/components/banner/BannerImg.js

- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

fix: 배너 로직 변경

---

front/src/components/components/Styled.js
front/src/components/includes/Footer.js
front/src/components/pages/RecruitmentDetail.js

- 요구사항
- footer 텍스트 수정
- 공고상세 페이지에서 요약사항 텍스트 강조
- 필요하면 첨부
- 참고 자료

fix: footer 텍스트 수정

---

front/src/components/components/Profile/CorporateDetails.js
front/src/components/components/Styled.js
front/src/components/components/resume/ResumeBasic.js
front/src/components/components/resume/ResumeCareer.js
front/src/components/components/resume/ResumeCertificate.js
front/src/components/components/resume/ResumeEducation.js
front/src/components/components/resume/ResumeSelfMd.js
front/src/components/data/mapLink.js
front/src/components/pages/ResumeDetails.js
front/src/components/pages/ResumeList.js
front/src/components/pages/profile/CorporateModify.js
front/src/components/pages/profile/IndividualModify.js

- 요구사항
- 이력서 목록 레이아웃 수정
- 이력서 작성, 수정, 조회 페이지 레이아웃 수정
- 공고 프로필 이미지 오류 수정
- 기업회원 주소 null 오류 수정
- mapLink 수정(Profile 개발용 삭제)
- 필요하면 첨부
- 참고 자료

fix: 이력서, 프로필 오류 및 레이아웃 수정

---

front/src/components/components/Chatting/ChatBox.js
front/src/components/components/Chatting/Message.js
front/src/components/components/Styled.js
front/src/components/components/banner/Banner.js
front/src/components/pages/RecruitLike.js

* 채팅날짜 변경.
* 리덕스 데브툴 비활성#####
( index.js 주석을 지우면 다시 활성가능)
* 공고찜목록 위로 사라지는것 해결
- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

fix: 채팅 날짜 변경

---

front/src/components/components/Chatting/Message.js
front/src/index.js

- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

fix: index.js커밋누락

---

front/src/components/components/ResumeItem.js
front/src/components/components/SubmitItem.js
front/src/components/pages/ResumeDetails.js

- 요구사항
- 지원된 이력서목록 모바일 레이아웃 수정
- 이력서 상세 페이지에서 수정버튼 숨김상태일 경우 레이아웃 수정
- 필요하면 첨부
- 참고 자료

Fix_지원된 이력서목록 모바일 레이아웃 수정

---

front/src/components/components/RecruitAdd/AnnounceLocation.js
front/src/components/data/DaumAddress.js
front/src/components/pages/profile/CorporateModify.js

- 요구사항
- 주소 검색 후 바로 좌표 찍히도록 고침
- 수정 페이지에서 주소 조회 가능하게 고침
- 필요하면 첨부
- 참고 자료

fix: 기업 프로필 주소 api 오류 수정

---

front/src/components/pages/RecruitmentDetail.js
src/main/java/com/jobseek/speedjobs/common/file/dto/File.java
src/main/java/com/jobseek/speedjobs/dto/banner/BannerResponse.java
src/main/java/com/jobseek/speedjobs/dto/banner/BannerResponses.java
src/main/java/com/jobseek/speedjobs/dto/tag/TagMap.java
src/main/java/com/jobseek/speedjobs/dto/tag/TagResponses.java
src/main/java/com/jobseek/speedjobs/service/BannerService.java

- 배너 캐시 적용
- HashMap -> EnumMap
- 공고 상시 채용인 경우 기간 안보이도록 수정
- 
- 필요하면 첨부
- 참고 자료

feat: 배너 캐시 적용

---

front/src/components/components/Profile/CorporateDetails.js
front/src/components/components/Profile/IndividualDetails.js
front/src/components/data/DaumAddress.js
front/src/components/pages/RecruitmentDetail.js

- 요구사항
- 주소 레이아웃 수정
- 엑박 오류 수정
- 필요하면 첨부
- 참고 자료

fix: 프로필, 이력서 레이아웃 수정

---

front/src/components/components/Chatting/ChatBox.js
front/src/components/components/Chatting/Message.js
front/src/components/components/Post.js
front/src/components/pages/Recruitment.js

- 요구사항
- 공고채팅 메세지에서 작성자 이름 표시
- 공고목록에서 공고상태 표시
- 공고목록에서 공고마감상태 디자인 변경
- 필요하면 첨부
- 참고 자료

fix: 공고채팅메세지에서 작성자 이름 표시

---

front/src/components/pages/Community.js
front/src/components/pages/Recruitment.js
front/src/components/pages/RecruitmentDetail.js
front/src/components/pages/home/AnnounceCard.js
front/src/components/pages/profile/CorporateModify.js

- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

fix: paging 오류수정. 오타수정.

---

front/src/components/components/Chatting/ChatBox.js
front/src/components/components/Post/PostList.js
front/src/components/pages/Community.js
front/src/components/pages/Recruitment.js
front/src/components/pages/RecruitmentDetail.js
front/src/components/pages/home/AnnounceCard.js
front/src/components/pages/profile/CorporateModify.js

- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

fix: 채팅방 환영메세지. 공고상태

---

src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitRepository.java
src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
src/main/java/com/jobseek/speedjobs/service/RecruitService.java

- 매일 자정에 공고 상태 변경
- 이력서 자기소개서 longtext로 변경
- resume 도메인 수정
- 필요하면 첨부
- 참고 자료

fix: 스케쥴러 수정

---

src/main/java/com/jobseek/speedjobs/domain/recruit/RecruitRepository.java
src/main/java/com/jobseek/speedjobs/domain/resume/Resume.java
src/main/java/com/jobseek/speedjobs/service/RecruitService.java

Revert "fix: 스케쥴러 수정"

---

front/src/pages/Community.js
front/src/pages/Recruitment.js
src/main/java/com/jobseek/speedjobs/service/RecruitService.java

- 요구사항
- 변경사항
- 필요하면 첨부
- 참고 자료

fix: 페이징 수정/공고 undefined수정

---

.gitignore
src/main/java/com/jobseek/speedjobs/service/UserService.java

- 유저 삭제 로직 수정(댓글 수 --)
- gitignore에 *.sql 추가

fix: 유저 삭제 로직 수정

---

README.md

- 도메인 주소 변경
- 무료 도메인 ml -> site로 변경
- cloudflare 프록싱
- 필요하면 첨부
- 참고 자료

fix: 도메인 주소 변경
